// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package sqlc

import (
	"time"
)

type Episode struct {
	ID            int32       `json:"id"`
	Name          string      `json:"name"`
	NumberSeries  int32       `json:"number_series"`
	NumberOverall int32       `json:"number_overall"`
	ReleaseDate   time.Time   `json:"release_date"`
	Description   string      `json:"description"`
	Body          string      `json:"body"`
	TranscriptUrl string      `json:"transcript_url"`
	PodcastID     int32       `json:"podcast_id"`
	SeriesID      int32       `json:"series_id"`
	LastUpdated   time.Time   `json:"last_updated"`
	FtsDocEn      interface{} `json:"fts_doc_en"`
}

type Podcast struct {
	ID          int32     `json:"id"`
	Name        string    `json:"name"`
	LastUpdated time.Time `json:"last_updated"`
}

type Series struct {
	ID          int32     `json:"id"`
	Name        string    `json:"name"`
	PodcastID   int32     `json:"podcast_id"`
	LastUpdated time.Time `json:"last_updated"`
}
